###
# notes from class
###

# r defaults to characters - you can recast as numbers

# use unique() to find how many unique values occur in a given column of a table
  # ex: unique(buoy_data_1985$DPD) --> gives 99 (only value in the column is 99)

# use <- NA to convert all values of a column in a table to NA 

# use na.rm = T to do functions to data and omit the NA values (such as taking mean
# of data without including NA bc if you don't it will give you NA in the end)

# tidyverse needs your data to be put in the form of data frames (but in tidyverse 
# they are called tibbles) -> cols in data frames are vectors 

###
# initial buoy project
###

# read in table
# between the file_root and tail is the year of the data that is wanted
# (this way you can easily loop through and read in each year's data)
file_root <- "https://www.ndbc.noaa.gov/view_text_file.php?filename=44013h" 
tail <- ".txt.gz&dir=data/historical/stdmet/"

# function to easily generate url to access buoy data per year 
# (connects file_root and tail via a particular year)
load_buoy_data <- function(year) {
  path <- paste0(file_root, year, tail)
}

path_1984 <- load_buoy_data("1984") # create the data path to access data from 1985

#read in information as a table into R
buoy_data_1984 <- read.table(path_1984, fill = T, header = T, sep = "") 


# data preprocessing
# initialize columns with incorrect values to NA
buoy_data_1984$WVHT <- NA

# check to make sure all of the data in this column is incorrect before replacing
unique(buoy_data_1984$DPD)
buoy_data_1984$DPD <- NA

# looking at air temp for 1985
# first checking if there are any NA values in the column 
# can't use this for this data though bc in this data set "NA" equivalent values are given 
# that of 999.0 so checking for NA will not tell you anything
nat <- which(is.na(buoy_data_1984$ATMP))
nat <- length(nat)

# writing and reading data
# save the airtemp data to a new file
airtemp_1984 <- buoy_data_1984$ATMP
saveRDS(airtemp_1984, file = "airtemp_1984.rdata")
# practice reading in the created data file and plot it
airtemp <- readRDS("airtemp_1984.rdata")

# plotting data
# fix airtemp to get rid of the "NA" type values (those with 999.0)
na_vals <- which(airtemp == 999) # gives index vals of vector that equal to 999.0
airtemp <- airtemp[-na_vals] # - a vector will drop the indices provided in the vector
plot(airtemp, type = "l") # use "l" to make it a line plot 

# read in and practice using the esquisse library to import data to make a graph 
library(esquisse)
# convert the read in airtemp data into the form of a data frame
# must be in the form of data frame first before using esquisser()
airtemp <- as.data.frame(airtemp)
at <- cbind(1:3459, airtemp) # binds together airtemp and an index counter
colnames(at) <- c("index", "temp")
# opens up esquisse that lets you make the data into different types of graphs
esquisser(at)

# create more types of graphs/plots with the ggplot2 library
library(ggplot2)
#ggplot -> got this by copying the code from the plot generated by esquisser()
ggplot(at) +
  aes(x = index, y = temp) +
  geom_line(colour = "#112446") +
  theme_minimal()
# use ggplot to create a plot of the city mpg and highway mpg of diff cars 
ggplot(mpg, aes(cty,hwy)) + geom_smooth(color = "red")
ggplot(mpg, aes(cty,hwy)) + geom_col()
